
create table bpm_delegate_info(
	id bigint generated by default as identity primary key,
	assignee varchar(200),
	attorney varchar(200),
	start_time timestamp,
	end_time timestamp,
	process_definition_id varchar(100),
	status int
);

-- insert into bpm_delegate_info(assignee,attorney,status) values('user1','user3',1);

create table bpm_delegate_history(
	id bigint generated by default as identity primary key,
	assignee varchar(200),
	attorney varchar(200),
	delegate_time timestamp,
	task_id varchar(100),
	status int
);
